#!/usr/bin/env bash
# script run nginx as nginx in 7 lines
pkill -f apache2
sudo sed -i " s/80/8080/g " /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
